### PR TITLE
Fixed Demo's CocoaPods issue

### PR DESCRIPTION
**Pull request by djbrooks111**
Fixed the Pods file and updated the README to reflect changes.  No code changes were made to original code, just to Pods.

### CODE REVIEW

**Comment by i110** [comment]
thanks a lot!

**Comment by i110** [comment]
@djbrooks111 You deleted ICTutorialOverlay.podspec. What did you intend? If it's a just mistake, I'll add it again.

**Comment by djbrooks111** [comment]
Don't you just need a pod file for pods to work? Why do you need a podspec file if you are just adding the pod to your project?

**Comment by i110** [comment]
@djbrooks111 You're right. I was mistaken because I had been away from Cocoapods for a while..

**Comment by i110** [comment]
@djbrooks111 I read some documents to catch up on recent Cocoapods way, and I guess that the podspec file is still necessary to publish this to Cocoapods/Specs (and as you know, this is definitely a Cocoapods library). Is this wrong?

The following documents refer to podspec file

> http://guides.cocoapods.org/making/making-a-cocoapod.html
> http://guides.cocoapods.org/making/getting-setup-with-trunk.html

and the popular libraries(like AFNetworking) have their own podspec files in their repositories.

Please correct me if I'm wrong.

**Pull request merged**
